version: "3.8"
services:
  api:
    build: .
    env_file:
      - .env
    environment:
      - TZ=Europe/Madrid
      - PYTHONUNBUFFERED=1
      - TIMING_DIR=/app/timings
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - C:/Users/desar/OneDrive/Desktop/DESARROLLO/Pruebas/zoa_flow_erp:/zoa_flow_erp
    networks:
      - zoa-network

networks:
  zoa-network:
    external: true
    name: zoa-network
