version: "3.8"
services:
  api:
    build: .
    env_file:
      - .env
    environment:
      - TZ=Europe/Madrid
      - PYTHONUNBUFFERED=1
      - TIMING_DIR=/app/timings
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    networks:
      - zoa-network

networks:
  zoa-network:
    name: zoa-network
