version: "3.8"
services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Madrid
      - WORKERS=4
    volumes:
      - .:/app
      - ./timings:/tmp/timings
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 4G
